### ISSUE TITLE
La galerie et l'équipe font souffler mon ordi

### ISSUE THREAD

**Issue by efondere** [Exocet-Polytechnique/exoweb#18]
@swemaster Change la taille des images 1-2Mo pour nos faces c'est too much

**Comment by swemaster** [comment]
Merci à @efondere pour ton issue, quand j'ai lu "souffler mon ordi" ça m'a fait assez rire.

On va fix ça prochainement. Si tu as d'autres issues n'hésite pas à en créer d'autres cela nous aide beaucoup, merci

**Comment by gumile** [comment]
bonjour, lorsque je rentre sur le site web exocet, j'aime les couleurs et l'esthétique, mais je n'arrive pas à interagir avec le site pendant 10 ou 15 secondes dû à un chargement d'image excessif. J'apprécierais que ce problème soit réglé afin que je puisse naviguer librement. Merci de votre collaboration

**Comment by wilf504** [comment]
Bonjour, pour poursuivre le commentaire de Guillaume, j'ai remarqué le même problème. En effet, 50Mb de photos sont chargés à chaque visite, particulièrement à cause de la galerie lorsque la cache est désactivée. Pour régler ce problème, la compression des images serait assez simple. Merci et au plaisir de recevoir une réponse avant que le site aie le temps de load!
